parameters:
    smile.find.class: Smile\EzHelpersBundle\Services\SmileFindService
    smile.content.class: Smile\EzHelpersBundle\Services\SmileContentService
    smile.convert.class: Smile\EzHelpersBundle\Services\SmileConvertService
    smile.user.class: Smile\EzHelpersBundle\Services\SmileUserService
    smile.services.class: Smile\EzHelpersBundle\Services\SmileServices

services:
    smile.find:
        class: '%smile.find.class%'
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.config.resolver.core"
            - "@smile.convert"
        lazy: true

    smile.content:
        class: '%smile.content.class%'
        arguments:
            - "@ezpublish.api.repository"
            - "@smile.find"
        lazy: true

    smile.convert:
        class: '%smile.convert.class%'
        arguments:
            - "@ezpublish.api.repository"
            - "@smile.content"
        lazy: true

    smile.user:
        class: '%smile.user.class%'
        arguments:
            - "@ezpublish.api.repository"
            - "@security.token_storage"
            - "@session"
            - "$security.token_interval_spec$"
        lazy: true

    smile.services:
        class: '%smile.services.class%'
        arguments:
            - "@smile.content"
            - "@smile.convert"
            - "@smile.user"
            - "@smile.find"
        lazy: true